INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (101, 01, 100, '놀이터', '놀이터','재미있는놀이터','블라블라','주차장완비','서울','동작동', '대명빌딩101', '썸네일주소', '승인', '놀이터.COM', '주의사항없음', '0' );

INSERT INTO PLACECATEGORY (PC_NO, PC_NAME) VALUES (100,'놀이터');

SELECT B.*
			FROM (SELECT ROWNUM RN , A.P_TITLE, A.RV_CONTENT, A.RV_STAR, A.M_ID
				FROM (SELECT RV.*, P.*, M.*
					FROM REVIEW RV LEFT JOIN PLACE P ON RV.P_NO=P.P_NO
					LEFT JOIN MEMBER M ON RV.M_NO = M.M_NO
					WHERE P.P_DELETE = 0
					AND P.P_CONFIRM LIKE '승인'
					AND P.S_NO=01) A) B
			WHERE RN BETWEEN #{param2} AND #{param3}



INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (100, 100, '음공 스튜디오 키친01', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (101, 100, '음공 스튜디오 키친02', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (102, 100, '음공 스튜디오 키친03', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (103, 100, '음공 스튜디오 키친04', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (105, 100, '음공 스튜디오 키친05', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (501, 100, '음공 스튜디오 키친06', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (511, 100, '음공 스튜디오 키친07', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (521, 100, '음공 스튜디오 키친08', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (531, 100, '음공 스튜디오 키친09', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (541, 100, '음공 스튜디오 키친10', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');



INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (111, 01, 501, '2021-02-08', 01, '예약', 10000, 01, '예약대기', 'RES_REQUIREMENT 01');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (112), 02, 501, '2021-01-09', 02, 'RES_STATE 02', 10000, 02, '예약대기', 'RES_REQUIREMENT 02');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (113, 03, 501, '2021-03-10', 03, 'RES_STATE 03', 20000, 03, '예약대기', 'RES_REQUIREMENT 03');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (114, 04, 501, '2021-03-10', 04, 'RES_STATE 04', 04, 04, '예약대기', 'RES_REQUIREMENT 04');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (115, 05, 501, '2021-03-10', 05, 'RES_STATE 05', 05, 05, '예약대기', 'RES_REQUIREMENT 05');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (06, 06, 06, '2021-03-11', 06, 'RES_STATE 06', 06, 06, '예약대기', 'RES_REQUIREMENT 06');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (07, 07, 07, '2021-03-12', 07, 'RES_STATE 07', 07, 07, '예약대기', 'RES_REQUIREMENT 07');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (08, 08, 08, '2021-03-13', 08, 'RES_STATE 08', 08, 08, '예약대기', 'RES_REQUIREMENT 08');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (09, 09, 09, '2021-03-14', 09, 'RES_STATE 09', 09, 09, '예약대기', 'RES_REQUIREMENT 09');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (10, 10, 10, '2021-03-15', 10, 'RES_STATE 10', 10, 10, '예약대기', 'RES_REQUIREMENT 10');



INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (121, 01, 101, 0, 01, 'RV_IMG01.jpg', SYSDATE, SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (122, 01, 101, 0, 02, 'RV_IMG02.jpg', '21-1-20', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (123, 03, 101, 0, 03, 'RV_IMG03.jpg', '21-1-21', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (124, 04, 101, 0, 04, 'RV_IMG04.jpg', '21-1-22', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (125, 05, 101, 0, 05, 'RV_IMG05.jpg', '21-1-23', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (126, 05, 101, 0, 05, 'RV_IMG06.jpg', '21-1-24', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (127, 05, 101, 0, 05, 'RV_IMG07.jpg', '21-1-25', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (128, 07, 101, 0, 04, 'RV_IMG08.jpg', '21-1-26', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (129, 07, 101, 0, 04, 'RV_IMG09.jpg', '21-1-27', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (130, 10, 101, 0, 04, 'RV_IMG10.jpg', '21-1-28', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (131, 10, 102, 0, 03, 'RV_IMG11.jpg', '21-1-29', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (132, 10, 102, 0, 04, 'RV_IMG12.jpg', '21-1-30', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (133, 10, 102, 0, 01, 'RV_IMG13.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (134, 10, 102, 0, 01, 'RV_IMG14.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (135, 10, 102, 0, 03, 'RV_IMG15.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (136, 10, 102, 1, 02, 'RV_IMG16.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (137, 11, 102, 1, 03, 'RV_IMG17.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (138, 11, 102, 1, 02, 'RV_IMG18.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (139, 13, 102, 1, 02, 'RV_IMG19.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (140, 15, 102, 1, 05, 'RV_IMG20.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');

INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member01', '1111', '010-1111-1101', '윤성민', '1998-01-01', '윤조장', 'dpwls6787@naver.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member02', '1111', '010-1111-1102', '김성민', '1998-02-01', '김조장', 'member02@naver.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member03', '1111', '010-1111-1103', '정성민', '1998-03-01', '정조장', 'member03@naver.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member04', '1111', '010-1111-1104', '박성민', '1998-04-01', '박조장', 'member04@naver.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member05', '1111', '010-1111-1105', '윤재혁', '1995-05-01', '혁재윤', 'member05@naver.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member06', '1111', '010-1111-1106', '김재혁', '1995-06-01', '혁재김', 'member06@naver.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member07', '1111', '010-1111-1107', '정재혁', '1995-07-01', '혁재정', 'member07@naver.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member08', '1111', '010-1111-1108', '박재혁', '1995-08-01', '혁재박', 'member08@nate.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member09', '1111', '010-1111-1109', '윤예진', '1997-09-01', '진예윤', 'member09@nate.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member10', '1111', '010-1111-1110', '김예진', '1997-10-01', '진예김', 'member10@nate.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member11', '1111', '010-1111-1111', '정예진', '1997-11-01', '진예정', 'member11@nate.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member12', '1111', '010-1111-1112', '박예진', '1997-12-01', '진예박', 'member12@nate.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member13', '1111', '010-1111-1113', '윤빛찬', '1992-01-01', '찬빛윤', 'member13@nate.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member14', '1111', '010-1111-1114', '김빛찬', '1992-02-01', '찬빛김', 'member14@nate.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member15', '1111', '010-1111-1115', '정빛찬', '1992-03-01', '찬빛정', 'member15@google.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member16', '1111', '010-1111-1116', '박빛찬', '1992-04-01', '찬빛박', 'member16@google.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member17', '1111', '010-1111-1117', '윤재성', '1992-03-01', '성재윤', 'member17@google.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member18', '1111', '010-1111-1118', '김재성', '1992-04-01', '성재김', 'member18@google.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member19', '1111', '010-1111-1119', '정재성', '1992-05-01', '성재정', 'member19@google.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'member20', '1111', '010-1111-1120', '박재성', '1992-06-10', '성재박', 'member20@google.com', sysdate, 1);
INSERT INTO MEMBER (M_NO, M_ID, M_PW, M_PHONE, M_NAME, M_BIRTH, M_NICK, M_EMAIL, M_REGDATE, M_AGREEMENT) VALUES (MEMBER_SEQ.NEXTVAL, 'admin', 'baraonadmin1111', '010-9999-9999', '관리자', '1992-12-31', '보스', 'admin@google.com', sysdate, 1);



INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (01, 01, 01, '음공 스튜디오 앤 키친', '음공 스튜디오&키친', '음공은 천천히 머물다가는 따뜻한 공간입니다.', 'P_CONTENT1', '["시설안내입니다.1","시설안내입니다.2"]', '서울특별시 마포구 연남동 224-6', '연남동', '1층 음공 스튜디오&키친', '["P_IMG01.jpg"]', '승인', 'P_URL 01', '["주의1","주의2","주의3"]', 0);
INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (01, 01, 02, '음공 스튜디오 앤 키친', '음공 스튜디오&키친', '음공은 천천히 머물다가는 따뜻한 공간입니다.', 'P_CONTENT1', '["시설안내입니다.1","시설안내입니다.2"]', '서울특별시 마포구 연남동 224-6', '연남동', '1층 음공 스튜디오&키친', '["P_IMG01.jpg"]', '승인', 'P_URL 01', '["주의1","주의2","주의3"]', 1);
INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (01, 01, 01, '음공 스튜디오 앤 키친', '음공 스튜디오&키친', '음공은 천천히 머물다가는 따뜻한 공간입니다.', 'P_CONTENT1', '["시설안내입니다.1","시설안내입니다.2"]', '서울특별시 마포구 연남동 224-6', '연남동', '1층 음공 스튜디오&키친', '["P_IMG01.jpg"]', '승인', 'P_URL 01', '["주의1","주의2","주의3"]', 0);


SELECT B.*
			FROM (SELECT ROWNUM RN , A.P_TITLE, A.RV_CONTENT, A.RV_STAR, A.M_ID
				FROM (SELECT RV.*, P.*, M.*
					FROM REVIEW RV LEFT JOIN PLACE P ON RV.P_NO=P.P_NO
					LEFT JOIN MEMBER M ON RV.M_NO = M.M_NO
					WHERE P.P_DELETE = 0
					AND P.P_CONFIRM LIKE '승인'
					AND P.S_NO=01) A) B
			WHERE RN BETWEEN 1 AND 5




