INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (100, 01, 100, '놀이터', '놀이터','재미있는놀이터','블라블라','주차장완비','서울','동작동', '대명빌딩101', '썸네일주소', '승인대기중', '놀이터.COM', '주의사항없음', '0' );

INSERT INTO PLACECATEGORY (PC_NO, PC_NAME) VALUES (100,'놀이터');





INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (100, 01, '음공 스튜디오 키친01', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (101, 01, '음공 스튜디오 키친02', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (102, 01, '음공 스튜디오 키친03', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (103, 01, '음공 스튜디오 키친04', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (105, 01, '음공 스튜디오 키친05', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (02, 01, '음공 스튜디오 키친06', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (03, 01, '음공 스튜디오 키친07', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (04, 01, '음공 스튜디오 키친08', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (05, 01, '음공 스튜디오 키친09', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');
INSERT INTO PLACEOPTION (PO_NO, P_NO, PO_NAME, PO_MIN, PO_MAX, PO_DAYPRICE, PO_HOLIDAY, PO_IMG, PO_FXILITY) VALUES (05, 01, '음공 스튜디오 키친10', 2, 15, 40000, 50000, 'PO_IMG101.jpg', '[tv, 주류반입가능, 마이크]');



INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (01, 01, 01, '2021-02-08', 01, '예약', 10000, 01, '예약대기', 'RES_REQUIREMENT 01');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (02, 02, 02, '2021-01-09', 02, 'RES_STATE 02', 10000, 02, '예약대기', 'RES_REQUIREMENT 02');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (03, 03, 03, '2021-03-10', 03, 'RES_STATE 03', 20000, 03, '예약대기', 'RES_REQUIREMENT 03');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (04, 04, 04, '2021-03-10', 04, 'RES_STATE 04', 04, 04, '예약대기', 'RES_REQUIREMENT 04');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (05, 05, 05, '2021-03-10', 05, 'RES_STATE 05', 05, 05, '예약대기', 'RES_REQUIREMENT 05');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (06, 06, 06, '2021-03-11', 06, 'RES_STATE 06', 06, 06, '예약대기', 'RES_REQUIREMENT 06');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (07, 07, 07, '2021-03-12', 07, 'RES_STATE 07', 07, 07, '예약대기', 'RES_REQUIREMENT 07');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (08, 08, 08, '2021-03-13', 08, 'RES_STATE 08', 08, 08, '예약대기', 'RES_REQUIREMENT 08');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (09, 09, 09, '2021-03-14', 09, 'RES_STATE 09', 09, 09, '예약대기', 'RES_REQUIREMENT 09');
INSERT INTO RESERVATION (RES_NO, M_NO, PO_NO, RES_DATE, RES_PEOPLE, RES_STATE, RES_PRICE, RES_APPLYNUM, RES_PURPOSE, RES_REQUIREMENT) VALUES (10, 10, 10, '2021-03-15', 10, 'RES_STATE 10', 10, 10, '예약대기', 'RES_REQUIREMENT 10');



INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (01, 01, 01, 0, 01, 'RV_IMG01.jpg', SYSDATE, SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (02, 01, 01, 0, 02, 'RV_IMG02.jpg', '21-1-20', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (03, 03, 01, 0, 03, 'RV_IMG03.jpg', '21-1-21', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (04, 04, 01, 0, 04, 'RV_IMG04.jpg', '21-1-22', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (05, 05, 01, 0, 05, 'RV_IMG05.jpg', '21-1-23', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (06, 05, 01, 0, 05, 'RV_IMG06.jpg', '21-1-24', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (07, 05, 01, 0, 05, 'RV_IMG07.jpg', '21-1-25', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (08, 07, 01, 0, 04, 'RV_IMG08.jpg', '21-1-26', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (09, 07, 01, 0, 04, 'RV_IMG09.jpg', '21-1-27', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (10, 10, 01, 0, 04, 'RV_IMG10.jpg', '21-1-28', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (11, 10, 01, 0, 03, 'RV_IMG11.jpg', '21-1-29', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (12, 10, 01, 0, 04, 'RV_IMG12.jpg', '21-1-30', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (13, 10, 01, 0, 01, 'RV_IMG13.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (14, 10, 01, 0, 01, 'RV_IMG14.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (15, 10, 01, 0, 03, 'RV_IMG15.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (16, 10, 01, 1, 02, 'RV_IMG16.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (17, 11, 01, 1, 03, 'RV_IMG17.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (18, 11, 01, 1, 02, 'RV_IMG18.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (19, 13, 01, 1, 02, 'RV_IMG19.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');
INSERT INTO REVIEW (RV_NO, M_NO, P_NO, RV_DELETE, RV_STAR, RV_IMG, RV_POSTDATE, RV_MODIFYDATE, RV_CONTENT) VALUES (20, 15, 01, 1, 05, 'RV_IMG20.jpg', '21-1-31', SYSDATE, '재밌었습니다. 재밌었습니다. 재밌었습니다. 재밌었습니다.');

INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (01, 01, 01, '음공 스튜디오 앤 키친', '음공 스튜디오&키친', '음공은 천천히 머물다가는 따뜻한 공간입니다.', 'P_CONTENT1', '["시설안내입니다.1","시설안내입니다.2"]', '서울특별시 마포구 연남동 224-6', '연남동', '1층 음공 스튜디오&키친', '["P_IMG01.jpg"]', '승인', 'P_URL 01', '["주의1","주의2","주의3"]', 0);
INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (01, 01, 02, '음공 스튜디오 앤 키친', '음공 스튜디오&키친', '음공은 천천히 머물다가는 따뜻한 공간입니다.', 'P_CONTENT1', '["시설안내입니다.1","시설안내입니다.2"]', '서울특별시 마포구 연남동 224-6', '연남동', '1층 음공 스튜디오&키친', '["P_IMG01.jpg"]', '승인', 'P_URL 01', '["주의1","주의2","주의3"]', 1);
INSERT INTO PLACE (P_NO, S_NO, PC_NO, P_TITLE, P_NAME, P_DESC, P_CONTENT, P_INFO, P_ADDR, P_BNAME, P_ADDRDETAIL, P_IMG, P_CONFIRM, P_URL, P_REMARK, P_DELETE) VALUES (01, 01, 01, '음공 스튜디오 앤 키친', '음공 스튜디오&키친', '음공은 천천히 머물다가는 따뜻한 공간입니다.', 'P_CONTENT1', '["시설안내입니다.1","시설안내입니다.2"]', '서울특별시 마포구 연남동 224-6', '연남동', '1층 음공 스튜디오&키친', '["P_IMG01.jpg"]', '승인', 'P_URL 01', '["주의1","주의2","주의3"]', 0);


SELECT B.*
			FROM (SELECT ROWNUM RN , A.P_TITLE, A.RV_CONTENT, A.RV_STAR, A.M_ID
				FROM (SELECT RV.*, P.*, M.*
					FROM REVIEW RV LEFT JOIN PLACE P ON RV.P_NO=P.P_NO
					LEFT JOIN MEMBER M ON RV.M_NO = M.M_NO
					WHERE P.P_DELETE = 0
					AND P.P_CONFIRM LIKE '승인'
					AND P.S_NO=01) A) B
			WHERE RN BETWEEN 1 AND 5




