DROP TABLE MEMBER;
DROP TABLE PLACECATEGORY;
DROP TABLE SELLER;
DROP TABLE PLACE;
DROP TABLE PLACEOPTION;
DROP TABLE RESERVATION;
DROP TABLE REVIEW;


DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE PLACECATEGORY_SEQ;
DROP SEQUENCE SELLER_SEQ;
DROP SEQUENCE PLACE_SEQ;
DROP SEQUENCE PLACEOPTION_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE REVIEW_SEQ;

-- MEMBER Table Create SQL
CREATE TABLE MEMBER
(
    M_NO           INT              PRIMARY KEY,
    M_ID           VARCHAR2(100)    NOT NULL UNIQUE, 
    M_PW           VARCHAR2(100)    NOT NULL, 
    M_PHONE        VARCHAR2(20)     NOT NULL UNIQUE, 
    M_NAME         VARCHAR2(50)     NOT NULL, 
    M_BIRTH        VARCHAR2(20)     NOT NULL, 
    M_NICK         VARCHAR2(100)    NOT NULL UNIQUE, 
    M_EMAIL        VARCHAR2(100)    NOT NULL UNIQUE, 
    M_REGDATE      DATE             NOT NULL, 
    M_AUTH         INT              NOT NULL, 
    M_AGREEMENT    INT              NOT NULL
);


CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;


-- PLACECATEGORY Table Create SQL
CREATE TABLE PLACECATEGORY
(
    PC_NO      INT              PRIMARY KEY, 
    PC_NAME    VARCHAR2(100)    NULL
);

CREATE SEQUENCE PLACECATEGORY_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- SELLER Table Create SQL
CREATE TABLE SELLER
(
    S_NO           INT             PRIMARY KEY, 
    S_ID           VARCHAR2(100)    NOT NULL UNIQUE, 
    S_PW           VARCHAR2(100)    NOT NULL ,
    S_PHONE        VARCHAR2(20)     NOT NULL UNIQUE,
    S_NAME         VARCHAR2(50)     NOT NULL,
    S_BIRTH        VARCHAR2(20)     NOT NULL,
    S_EMAIL        VARCHAR2(100)    NOT NULL UNIQUE,
    S_REGDATE      DATE             NOT NULL, 
    S_AUTH         INT              NOT NULL, 
    S_AGREEMENT    INT              NOT NULL, 
    S_COMPANYNO    VARCHAR2(50)     NOT NULL 
);


CREATE SEQUENCE SELLER_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- PLACE Table Create SQL
CREATE TABLE PLACE
(
    P_NO         INT               PRIMARY KEY, 
    S_NO         INT               NOT NULL REFERENCES SELLER (S_NO), 
    PC_NO        INT               NOT NULL REFERENCES PLACECATEGORY (PC_NO), 
    P_TITLE      VARCHAR2(100)     NOT NULL, 
    P_DESC       VARCHAR2(200)     NOT NULL, 
    P_CONTENT    VARCHAR2(4000)    NOT NULL, 
    P_INFO       VARCHAR2(1000)    NOT NULL, 
    P_NAME       VARCHAR2(200)     NOT NULL, 
    P_ADDR       VARCHAR2(200)     NOT NULL, 
    P_STAR       INT               NULL, 
    P_IMG        VARCHAR2(50)      NULL, 
    P_CONFIRM    INT               , 
    P_URL        VARCHAR2(100)     NULL, 
    P_REMARK     VARCHAR2(2000)    NULL, 
    P_DELETE     INT
);


CREATE SEQUENCE PLACE_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;



-- PLACEOPTION Table Create SQL
CREATE TABLE PLACEOPTION
(
    PO_NO          INT             PRIMARY KEY, 
    P_NO           INT             NOT NULL REFERENCES PLACE (P_NO), 
    PO_MIN         INT             NOT NULL, 
    PO_MAX         INT             NOT NULL, 
    PO_DAYPRICE    INT             NOT NULL, 
    PO_HOLIDAY     INT             NULL, 
    PO_ADDPRICE    INT             NULL, 
    PO_IMG1        VARCHAR2(50)    NULL, 
    PO_IMG2        VARCHAR2(50)    NULL, 
    PO_IMG3        VARCHAR2(50)    NULL, 
    PO_FXILITY     VARCHAR2(100)   NULL
);

CREATE SEQUENCE PLACEOPTION_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


-- RESERVATION Table Create SQL
CREATE TABLE RESERVATION
(
    RES_NO        INT             PRIMARY KEY, 
    M_NO          INT             NOT NULL REFERENCES MEMBER (M_NO), 
    PO_NO         INT             NOT NULL REFERENCES PLACEOPTION (PO_NO), 
    RES_DATE      DATE            NOT NULL, 
    RES_PEOPLE    INT             NOT NULL, 
    RES_STATE     VARCHAR2(20)    NULL
);


CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- REVIEW Table Create SQL
CREATE TABLE REVIEW
(
    RV_NO        INT               PRIMARY KEY, 
    M_NO         INT               NOT NULL REFERENCES MEMBER (M_NO), 
    P_NO         INT               NOT NULL REFERENCES PLACE (P_NO), 
    RV_DELETE    INT               NULL, 
    RV_STAR      INT               NULL, 
    RV_IMG       VARCHAR2(4000)    NULL
);


CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

SELECT P.P_NO, PC.PC_NAME, MIN(PO.PO_DAYPRICE) AS MINPRICE, MAX(PO.PO_MAX) AS MAXPEOPLE, COUNT(R.P_NO) AS RVCOUNT
  FROM PLACE P LEFT JOIN PLACECATEGORY PC ON P.PC_NO = PC.PC_NO
			   LEFT JOIN PLACEOPTION PO ON P.P_NO = PO.P_NO
			   LEFT JOIN REVIEW R ON P.P_NO = R.P_NO
WHERE R.RV_DELETE = 0
GROUP BY P.P_NO, PC.PC_NAME

SELECT * FROM REVIEW;
SELECT * FROM PLACEOPTION;