-- PLACECATEGORY Table Create SQL
CREATE TABLE PLACECATEGORY
(
    PC_NO      INT              NOT NULL, 
    PC_NAME    VARCHAR2(100)    NULL, 
    CONSTRAINT PLACECATEGORY_PK PRIMARY KEY (PC_NO)
);
/

CREATE SEQUENCE PLACECATEGORY_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
/

--DROP SEQUENCE PLACECATEGORY_SEQ;
/

COMMENT ON COLUMN PLACECATEGORY.PC_NO IS '장소카테고리번호'
/

COMMENT ON COLUMN PLACECATEGORY.PC_NAME IS '카테고리'
/

-- SELLER Table Create SQL
CREATE TABLE SELLER
(
    S_NO           INT              NOT NULL, 
    S_ID           VARCHAR2(100)    NOT NULL, 
    S_PW           VARCHAR2(100)    NOT NULL, 
    S_PHONE        VARCHAR2(20)     NOT NULL, 
    S_NAME         VARCHAR2(50)     NOT NULL, 
    S_BIRTH        VARCHAR2(20)     NOT NULL, 
    S_EMAIL        VARCHAR2(100)    NOT NULL, 
    S_REGDATE      DATE             DEFAULT SYSDATE NOT NULL, 
    S_AUTH         INT              DEFAULT 0 NOT NULL, 
    S_AGREEMENT    INT              NOT NULL, 
    S_COMPANYNO    VARCHAR2(50)     NOT NULL, 
    CONSTRAINT SELLER_PK PRIMARY KEY (S_NO)
);
/

CREATE SEQUENCE SELLER_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
/

--DROP SEQUENCE SELLER_SEQ;
/

COMMENT ON COLUMN SELLER.S_NO IS '판매자번호'
/

COMMENT ON COLUMN SELLER.S_ID IS '판매자아이디'
/

COMMENT ON COLUMN SELLER.S_PW IS '판매자비밀번호'
/

COMMENT ON COLUMN SELLER.S_PHONE IS '판매자연락처'
/

COMMENT ON COLUMN SELLER.S_NAME IS '판매자이름'
/

COMMENT ON COLUMN SELLER.S_BIRTH IS '생년월일'
/

COMMENT ON COLUMN SELLER.S_EMAIL IS '판매자이메일'
/

COMMENT ON COLUMN SELLER.S_REGDATE IS '가입일'
/

COMMENT ON COLUMN SELLER.S_AUTH IS '인증'
/

COMMENT ON COLUMN SELLER.S_AGREEMENT IS '약관동의'
/

COMMENT ON COLUMN SELLER.S_COMPANYNO IS '사업자번호'
/

ALTER TABLE SELLER
    ADD CONSTRAINT UC_S_ID UNIQUE (S_ID)
/

ALTER TABLE SELLER
    ADD CONSTRAINT UC_S_PHONE UNIQUE (S_PHONE)
/

ALTER TABLE SELLER
    ADD CONSTRAINT UC_S_EMAIL UNIQUE (S_EMAIL)
/


-- PLACE Table Create SQL
CREATE TABLE PLACE
(
    P_NO         INT               NOT NULL, 
    S_NO         INT               NOT NULL, 
    PC_NO        INT               NOT NULL, 
    P_TITLE      VARCHAR2(100)     NOT NULL, 
    P_DESC       VARCHAR2(200)     NOT NULL, 
    P_CONTENT    VARCHAR2(4000)    NOT NULL, 
    P_INFO       VARCHAR2(1000)    NOT NULL, 
    P_NAME       VARCHAR2(200)     NOT NULL, 
    P_ADDR       VARCHAR2(200)     NOT NULL, 
    P_STAR       INT               NULL, 
    P_IMG        VARCHAR2(50)      NULL, 
    P_CONFIRM    INT               DEFAULT DEFALUT(0) NOT NULL, 
    P_URL        VARCHAR2(100)     NULL, 
    P_REMARK     VARCHAR2(2000)    NULL, 
    P_DELETE     INT               DEFAULT 0 NULL, 
    CONSTRAINT PLACE_PK PRIMARY KEY (P_NO)
);
/

CREATE SEQUENCE PLACE_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
/

--DROP SEQUENCE PLACE_SEQ;
/


COMMENT ON COLUMN PLACE.P_NO IS '게시번호'
/

COMMENT ON COLUMN PLACE.S_NO IS '판매자번호'
/

COMMENT ON COLUMN PLACE.PC_NO IS '카테고리번호'
/

COMMENT ON COLUMN PLACE.P_TITLE IS '공간제목'
/

COMMENT ON COLUMN PLACE.P_DESC IS '공간한줄설명'
/

COMMENT ON COLUMN PLACE.P_CONTENT IS '공간설명'
/

COMMENT ON COLUMN PLACE.P_INFO IS '시설안내'
/

COMMENT ON COLUMN PLACE.P_NAME IS '업체명'
/

COMMENT ON COLUMN PLACE.P_ADDR IS '위치'
/

COMMENT ON COLUMN PLACE.P_STAR IS '별점'
/

COMMENT ON COLUMN PLACE.P_IMG IS '썸네일'
/

COMMENT ON COLUMN PLACE.P_CONFIRM IS '승인여부'
/

COMMENT ON COLUMN PLACE.P_URL IS '홈페이지'
/

COMMENT ON COLUMN PLACE.P_REMARK IS '비고'
/

COMMENT ON COLUMN PLACE.P_DELETE IS '삭제여부'
/

ALTER TABLE PLACE
    ADD CONSTRAINT FK_PLACE_PC_NO_PLACECATEGORY_P FOREIGN KEY (PC_NO)
        REFERENCES PLACECATEGORY (PC_NO)
/

ALTER TABLE PLACE
    ADD CONSTRAINT FK_PLACE_S_NO_SELLER_S_NO FOREIGN KEY (S_NO)
        REFERENCES SELLER (S_NO)
/


-- PLACEOPTION Table Create SQL
CREATE TABLE PLACEOPTION
(
    PO_NO          INT             NOT NULL, 
    P_NO           INT             NOT NULL, 
    PO_MIN         INT             NOT NULL, 
    PO_MAX         INT             NOT NULL, 
    PO_DAYPRICE    INT             NOT NULL, 
    PO_HOLIDAY     INT             NULL, 
    PO_ADDPRICE    INT             NULL, 
    PO_IMG1        VARCHAR2(50)    NULL, 
    PO_IMG2        VARCHAR2(50)    NULL, 
    PO_IMG3        VARCHAR2(50)    NULL, 
    PO_FXILITY     VARCHAR2(100)   NULL   
);
/

CREATE SEQUENCE PLACEOPTION_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
/

--DROP SEQUENCE PLACEOPTION_SEQ;
/

COMMENT ON COLUMN PLACEOPTION.PO_NO IS '인덱스'
/

COMMENT ON COLUMN PLACEOPTION.P_NO IS '게시번호'
/

COMMENT ON COLUMN PLACEOPTION.PO_MIN IS '최소인원'
/

COMMENT ON COLUMN PLACEOPTION.PO_MAX IS '최대인원'
/

COMMENT ON COLUMN PLACEOPTION.PO_DAYPRICE IS '가격'
/

COMMENT ON COLUMN PLACEOPTION.PO_HOLIDAY IS '공휴일가격'
/

COMMENT ON COLUMN PLACEOPTION.PO_ADDPRICE IS '인당추가가격'
/

COMMENT ON COLUMN PLACEOPTION.PO_IMG1 IS '사진1'
/

COMMENT ON COLUMN PLACEOPTION.PO_IMG2 IS '사진2'
/

COMMENT ON COLUMN PLACEOPTION.PO_IMG3 IS '사진3'
/

COMMENT ON COLUMN PLACEOPTION.PO_FXILITY IS '편의시설'
/

ALTER TABLE PLACEOPTION
    ADD CONSTRAINT FK_PLACEOPTION_P_NO_PLACE_P_NO FOREIGN KEY (P_NO)
        REFERENCES PLACE (P_NO)
/

ALTER TABLE PLACEOPTION
    ADD CONSTRAINT UC_P_NO UNIQUE (P_NO)
/

-- RESERVATION Table Create SQL
CREATE TABLE RESERVATION
(
    RES_NO        INT             NOT NULL, 
    M_NO          INT             NOT NULL, 
    PO_NO         INT             NOT NULL, 
    RES_DATE      DATE            NOT NULL, 
    RES_PEOPLE    INT             NOT NULL, 
    RES_STATE     VARCHAR2(20)    NULL, 
    CONSTRAINT RESERVATION_PK PRIMARY KEY (RES_NO)
);
/

CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
/

--DROP SEQUENCE RESERVATION(OR BOOKING)_SEQ;
/

COMMENT ON COLUMN RESERVATION.RES_NO IS '예약번호'
/

COMMENT ON COLUMN RESERVATION.M_NO IS '예약자'
/

COMMENT ON COLUMN RESERVATION.PO_NO IS '옵션인덱스'
/

COMMENT ON COLUMN RESERVATION.RES_DATE IS '예약날짜'
/

COMMENT ON COLUMN RESERVATION.RES_PEOPLE IS '예약인원'
/

COMMENT ON COLUMN RESERVATION.RES_STATE IS '예약상태'
/

ALTER TABLE RESERVATION
    ADD CONSTRAINT FK_RESERVATION_M_N FOREIGN KEY (M_NO)
        REFERENCES MEMBER (M_NO)
/

ALTER TABLE RESERVATION
    ADD CONSTRAINT FK_RESERVATION_PO_ FOREIGN KEY (PO_NO)
        REFERENCES PLACE_OPTION (PO_NO)
/


-- REVIEW Table Create SQL
CREATE TABLE REVIEW
(
    RV_NO        INT               NOT NULL, 
    M_NO         INT               NOT NULL, 
    P_NO         INT               NOT NULL, 
    RV_DELETE    INT               DEFAULT 0 NULL, 
    RV_STAR      INT               DEFAULT 0 NULL, 
    RV_IMG       VARCHAR2(4000)    NULL, 
    CONSTRAINT REVIEW_PK PRIMARY KEY (RV_NO)
);
/

CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
/

--DROP SEQUENCE REVIEW_SEQ;
/

COMMENT ON COLUMN REVIEW.RV_NO IS '리뷰번호'
/

COMMENT ON COLUMN REVIEW.M_NO IS '클럽장'
/

COMMENT ON COLUMN REVIEW.P_NO IS '업체번호'
/

COMMENT ON COLUMN REVIEW.RV_DELETE IS '삭제여부'
/

COMMENT ON COLUMN REVIEW.RV_STAR IS '별점'
/

COMMENT ON COLUMN REVIEW.RV_IMG IS '장소리뷰'
/

ALTER TABLE REVIEW
    ADD CONSTRAINT FK_REVIEW_P_NO_PLACE_P_NO FOREIGN KEY (P_NO)
        REFERENCES PLACE (P_NO)
/

ALTER TABLE REVIEW
    ADD CONSTRAINT FK_REVIEW_M_NO_MEMBER_M_NO FOREIGN KEY (M_NO)
        REFERENCES MEMBER (M_NO)
/
