-- 예진 사용
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (01, 'seller01', '1111', 'S_PHONE 01', 'S_NAME 01', 'S_BIRTH 01', 'dpwls6787@naver.com', sysdate, 1, 'S_COMPANYNO 01');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (02, 'seller02', '1111', 'S_PHONE 02', 'S_NAME 02', 'S_BIRTH 02', 'dpwls6787@nate.com', sysdate, 1, 'S_COMPANYNO 02');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (03, 'seller03', '1111', 'S_PHONE 03', 'S_NAME 03', 'S_BIRTH 03', 'S_EMAIL03@naver.com', sysdate, 1, 'S_COMPANYNO 03');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (04, 'seller04', '1111', 'S_PHONE 04', 'S_NAME 04', 'S_BIRTH 04', 'S_EMAIL04@naver.com', sysdate, 1, 'S_COMPANYNO 04');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (05, 'seller05', '1111', 'S_PHONE 05', 'S_NAME 05', 'S_BIRTH 05', 'S_EMAIL05@naver.com', sysdate, 1, 'S_COMPANYNO 05');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (06, 'seller06', '1111', 'S_PHONE 06', 'S_NAME 06', 'S_BIRTH 06', 'S_EMAIL06@naver.com', sysdate, 1, 'S_COMPANYNO 06');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (07, 'seller07', '1111', 'S_PHONE 07', 'S_NAME 07', 'S_BIRTH 07', 'S_EMAIL07@naver.com', sysdate, 1, 'S_COMPANYNO 07');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (08, 'seller08', '1111', 'S_PHONE 08', 'S_NAME 08', 'S_BIRTH 08', 'S_EMAIL08@naver.com', sysdate, 1, 'S_COMPANYNO 08');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (09, 'seller09', '1111', 'S_PHONE 09', 'S_NAME 09', 'S_BIRTH 09', 'S_EMAIL09@naver.com', sysdate, 1, 'S_COMPANYNO 09');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (10, 'seller10', '1111', 'S_PHONE 10', 'S_NAME 10', 'S_BIRTH 10', 'S_EMAIL10@naver.com', sysdate, 1, 'S_COMPANYNO 10');
INSERT INTO SELLER (S_NO, S_ID, S_PW, S_PHONE, S_NAME, S_BIRTH, S_EMAIL, S_REGDATE, S_AGREEMENT, S_COMPANYNO) VALUES (11, 'seller11', '1111', 'S_PHONE 11', 'S_NAME 11', 'S_BIRTH 11', 'S_EMAIL11@naver.com', sysdate, 1, 'S_COMPANYNO 11');

-- 장기
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '치맥, 책맥!', '치킨&맥주 + 책&맥주 = 치맥, 책맥!', '치킨과 맥주의 즐거움을 아는 당신 책과 맥주의 즐거움도 알아볼 시간', sysdate, TO_DATE('2021-03-07', 'YYYY-MM-DD'), TO_DATE('2021-04-15', 'YYYY-MM-DD'), 05, 10, 'chicken.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '김대리의 재테크 스쿨', '실제 수익 내는 재테크 스터디 누구나 할 수 있다', '초등학생들도 하는 주식 당신만 안 하고 있다 지금부터 시작하라', sysdate, TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2021-05-05', 'YYYY-MM-DD'), 01, 05, 'presentation.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '우리집 사용설명서', '내집 마련을 위한, 나만의 독립된 공간을 위한 가이드라인', '인스타그램, 페이스북에서 보던 예쁜 집을 나도 똑같이 할 수 있다', sysdate, TO_DATE('2021-03-15', 'YYYY-MM-DD'), TO_DATE('2021-03-22', 'YYYY-MM-DD'), 02, 05, 'furniture.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '노을 러너(Run with SunSet)', '아름다운 노을을 보면서 뛰어봐요', '퇴근 후 바로 집으로 들어가지 말고 다양한 사람들과 같이 뛰어봐요', sysdate, TO_DATE('2021-03-02', 'YYYY-MM-DD'), TO_DATE('2021-05-07', 'YYYY-MM-DD'), 05, 15, 'run.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 03, '직장인 프리다이빙 자격증반', '물 공포증 극복, 심신안정 등 당신의 한계에 도전해보세요', '프리다이빙은 자신의 한계를 극복하고 나아가 발전시킬 수 있는 좋은 운동이자 경험이 될 것 입니다.', sysdate, TO_DATE('2021-02-22', 'YYYY-MM-DD'), TO_DATE('2021-05-07', 'YYYY-MM-DD'), 10, 15, 'freediving.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '오토바이 동아리', '오늘은 우리가 고스트라이더', '스릴, 재미 등을 즐겨보세요', sysdate, TO_DATE('2021-02-28', 'YYYY-MM-DD'), TO_DATE('2021-03-02', 'YYYY-MM-DD'), 10, 15, 'motorcycle1.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '극강의 속도, 자신있는자만 오라', '전 세계 TOP10위 안에 드는 롤러코스터를 체험해보세요', '전세계적으로 많고 많은 롤러코스터 중 TOP10 안에 드는 롤러코스터를 한 번 도전해보세요', sysdate, TO_DATE('2021-03-22', 'YYYY-MM-DD'), TO_DATE('2021-04-22', 'YYYY-MM-DD'), 20, 25, '롤러코스터.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '독서, 마음의 양식', '하나의 책, 여러분의 생각을 공유해봐요', '사람마다 저마다 생각하는 방식은 다 다름니다. 책 하나를 읽고 자신만의 생각을 공유해봐요', sysdate, TO_DATE('2021-04-15', 'YYYY-MM-DD'), TO_DATE('2021-05-10', 'YYYY-MM-DD'), 2, 5, 'books.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '드림카 체험', '눈으로만 즐기던 드림카를 직접 타 보세요', '더 이상 저건 무슨 느낌일까라는 생각은 그만! 직접 타고 느껴보세요', sysdate, TO_DATE('2021-02-19', 'YYYY-MM-DD'), TO_DATE('2021-03-09', 'YYYY-MM-DD'), 2, 7, 'car.jpg', 0, 0);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 03, '주말 공원 산책', '주말이라고 집에만 있지 말고 공원에서 운동 한 번 해봐요', '주말이라고 맨날 집에서 뒹굴거리지 말고 밖으로 나와봐요. 이걸 보고 찔리면 일단 신청해봐요~ ', sysdate, TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2021-05-30', 'YYYY-MM-DD'), 30, 50, 'park.jpg', 0, 0);

-- 단기
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '치맥, 책맥!', '치킨&맥주 + 책&맥주 = 치맥, 책맥!', '치킨과 맥주의 즐거움을 아는 당신 책과 맥주의 즐거움도 알아볼 시간', sysdate, TO_DATE('2021-03-07', 'YYYY-MM-DD'), TO_DATE('2021-03-07', 'YYYY-MM-DD'), 05, 10, 'chicken.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '강아지 산책', '강아지들도 친구를 만나고 싶어해요!!', '강아지들도 사람들 처럼 많은 강아지들을 만나면서 유대감을 형성 할 수 있도록 해봐요~', sysdate, TO_DATE('2021-03-15', 'YYYY-MM-DD'), TO_DATE('2021-03-15', 'YYYY-MM-DD'), 05, 10, 'puppy.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '모닝 러너', '아름다운 일출을 보면서 뛰어봐요', '주말이라고 집에 있지말고 뜻 깊은 하루를 보내봐요', sysdate, TO_DATE('2021-03-02', 'YYYY-MM-DD'), TO_DATE('2021-03-02', 'YYYY-MM-DD'), 05, 15, 'train.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 03, '클라이밍', '보다 더 높게, 보다 더 빠르게', '보다 더 높은곳을 향해 뛰어봐요!!.', sysdate, TO_DATE('2021-02-22', 'YYYY-MM-DD'), TO_DATE('2021-02-22', 'YYYY-MM-DD'), 10, 15, 'climing.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '오토바이 동아리', '오늘은 우리가 고스트라이더', '스릴, 재미 등을 즐겨보세요', sysdate, TO_DATE('2021-02-28', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), 10, 15, 'motorcycle3.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 02, '극강의 속도', '전 세계 TOP10위 안에 드는 롤러코스터를 체험해보세요', '전세계적으로 많고 많은 롤러코스터 중 TOP10 안에 드는 롤러코스터를 한 번 도전해보세요', sysdate, TO_DATE('2021-03-22', 'YYYY-MM-DD'), TO_DATE('2021-03-22', 'YYYY-MM-DD'), 20, 25, '롤러코스터.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '동네 축구', '축구하고 싶은 당신 신청하라!', '22명이 모여야 할 수 있는 축구, 이제 동네 사람들끼리 모여서 해봐요', sysdate, TO_DATE('2021-04-15', 'YYYY-MM-DD'), TO_DATE('2021-04-15', 'YYYY-MM-DD'), 22, 24, 'soccer.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '드림카 체험', '눈으로만 즐기던 드림카를 직접 타 보세요', '더 이상 저건 무슨 느낌일까라는 생각은 그만! 직접 타고 느껴보세요', sysdate, TO_DATE('2021-02-19', 'YYYY-MM-DD'), TO_DATE('2021-03-09', 'YYYY-MM-DD'), 2, 7, 'car.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 03, '등산', '북한산 정상에서 인생샷 찍고 내려오기', '요새 등산이 유행이라고하죠~ 당신도 할 수 있어요', sysdate, TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2021-03-01', 'YYYY-MM-DD'), 30, 50, 'mountain.jpg', 0, 1);
INSERT INTO CLUB (C_NO, M_NO, C_TITLE, C_DESC, C_CONTENT, C_POSTDATE, C_STARTDATE, C_ENDDATE, C_MIN, C_MAX, C_MAINIMG, C_DELETE, C_PART) VALUES (CLUB_SEQ.NEXTVAL, 01, '김대리의 재테크 스쿨', '실제 수익 내는 재테크 스터디 누구나 할 수 있다', '초등학생들도 하는 주식 당신만 안 하고 있다 지금부터 시작하라', sysdate, TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2021-03-01', 'YYYY-MM-DD'), 01, 05, 'presentation.jpg', 0, 1);




